profile = "personal"

[features]
gui = true
nvim = true
tmux = true
zsh = true
fonts = true
proxy = false

[identity]
name = "User"
email = "user@example.com"

[editor]
default = "nvim"

[shell]
default = "zsh"
