[repos]
# zsh = "git@github.com:YOUR_NAME/zsh-config.git"
# nvim = "git@github.com:YOUR_NAME/nvim-config.git"
# scripts = "git@github.com:YOUR_NAME/scripts.git" # placeholder, replace with actual repo when use
# wallpapers = "git@github.com:YOUR_NAME/wallpapers.git" # placeholder, replace with actual repo when use

[repos.third_party]
tpm = "https://github.com/tmux-plugins/tpm.git"
